FROM nginx:1.25.3

#Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

#Copy custom nginx config
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

#Run nginx
CMD ["nginx", "-g", "daemon off;"]